// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"KPO-miniHW-1/services"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeContainer() *Container {
	vetClinic := services.NewVetClinic()
	zoo := services.NewZoo(vetClinic)
	container := &Container{
		Zoo:       zoo,
		VetClinic: vetClinic,
	}
	return container
}

// wire.go:

var ContainerSet = wire.NewSet(services.NewVetClinic, services.NewZoo, wire.Struct(new(Container), "Zoo", "VetClinic"))
